Drink Book Pull Request Test
KaloianK/internship_tasks pull request #1
Opened 2021-04-23 13:56 UTC by KaloianK

please approve :)

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        List<User> listOfUsers = new List<User>();
Should define visibility

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public virtual bool CanUserEnterTheClub(User user)
CanUserEnter is enough

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +
Empty new line

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +                listOfUsers.Add(user);
this.listOfUsers

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            return listOfUsers;
this.listOfUsers

2021-04-26 07:59 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +                userNamesInClubs.AppendJoin(".|.", userNamesArr);
TOP 🥇

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public int PriceOfWhiskey
Suggestions
1.  You can use the shorthand syntax for get /set: 
```suggestion
        public int PriceOfWhiskey
        {
             get => this.priceOfWhiskey;
             set => this.priceOfWhiskey = value;
        }
```

2.  You can make use of the Auto-Implemented properties. Ref: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +                return musicPlayed;
Use 'this' keyword to access class members.  It represents the “this” pointer of a class / stuct - the current instance of a class or stuct. 
Example:  `this.musicPlayed`

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Constants.cs
> +    class Constants
Always add visibility modifiers for classes / methods
`public class Constants`

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/DrinkBook.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Add git ignore

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/FolkClub.cs
> +            else return true;
Formatting

1. Remove unneeded lines

2. Always add {} for statements

3. Is the else really needed?

4. base.CanUserEnterTheClub(user) == false <=> !base.CanUserEnterTheClub(user)

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +        private int priceOfWhiskey;
Try to use more simple names - whiskeyPrice, users are enough

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public Club(string name, int priceOfWhiskey, int priceOfVodka, int capacity)
Class member orders should be: fields (private, then public), constructors, properties (private, public) and after that methods

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +            this.priceOfWhiskey = priceOfWhiskey;
Shouldn't you set the properties values here, instead of the field ones? `this.Name = name`

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Club.cs
> +
Remove empty lines

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/Constants.cs
> +        public const int MAX_CAPACITY_HouseClub = int.MaxValue;
Use only upper case for consts

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/FolkClub.cs
> +        private string singer;
Shouldn't there be e property for singer + validation?

2021-04-26 07:59 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public ListsOfClubs()
You don't need the empty constructor, you have one by default

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +                return name;
this.name

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public int PriceOfWhiskey
Also you can set negative values for prices. You should add validation

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public int ConvertDrinkableAlcoholToMoney(int drinkableWhiskeys, int drinkableVodkas)
Typo in name. Money should be decimal. Use simpler names

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            currentPriceOfWhiskey = this.PriceOfWhiskey * drinkableWhiskeys;
why not define it directly when initializing variable

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            currentPriceOfWhiskey = this.PriceOfWhiskey * drinkableWhiskeys;
Also name is misleading

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            fullPriceForAlcohol = currentPriceOfVodka + currentPriceOfWhiskey;
you can directly return the value

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            if (CanUserEnterTheClub(user) == true)
CanUserEnterTheClub(user) is enough

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public List<User> RemoveUserFromClub(User user)
RemoveUser is enough, because Methods should not contain their class name as it is implied by it.

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/HouseClub.cs
> +            base.CanUserEnterTheClub(user);
This line has no purpose in current implementation. `base.CanUserEnterTheClub(user)` returns a value which you never use.

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        List<Club> listOfClubs = new List<Club>();
Should define visibility

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public void AddClubToTheList(Club club)
AddClub is enough in the context of the class

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +                clubNames.Append(this.listOfClubs[i].Name + ", ");
This way the string will always have a comma at the end

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public void GetAllClubsPrices()
You are not GET-ing anything. Different name should be used

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +
Empty new line

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +                bool canUserEnter = club.CanUserEnterTheClub(user);
You do not use canUserEnter anywhere, maybe you meant using canWeAddTheUserInTheClub

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +            bool canWeAddTheUserInTheClub = false;
canUserEnter is a better name

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/RockClub.cs
> +            base.CanUserEnterTheClub(user);
This line has no purpose in current implementation.

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return name;
`this.name` or return simple constructor as per Tanya's suggestion: You can make use of the Auto-Implemented properties. Ref: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return age;
this. missing

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return budget;
this. missing

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return drinkableWhiskeys;
this. missing

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return drinkableVodkas;
this. missing

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +                return preferredMusic;
this. missing

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +            this.name = "";
this.Name and so on

2021-04-26 08:36 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +            this.name = name;
this.Name and so on

2021-04-27 09:28 UTC, GeorgiDyulgerov requested changes

2021-04-27 09:28 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +﻿using System;
Test

2021-04-27 14:02 UTC, GeorgiDyulgerov requested changes

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            this.name = "";
Use the properties `this.Name`, not the fields `this.name` and so on for setting values

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public Club(string name, int whiskeyPrice, int vodkaPrice, int capacity)
Class member orders should be: fields (private, then public), constructors, properties (private, public) and after that methods

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public int CostOfAlcoholToDrink(int whiskeysToDrink, int vodkasToDrink)
Return type should be decimal and the name does not indicate you are GETing a result

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            int costOfAlcohol = 0;
Money should be decimal

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            return costOfAlcohol = convertedVodkaPrice + convertedWhiskeyPrice;
`convertedVodkaPrice + convertedWhiskeyPrice` is enougn, also this way i think it would return bool instead of decimal/int

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +
Unneeded new line

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +            }
new line after closing `}`

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +                this.listOfUsers.Add(user);
Should be the property this.ListOfUsers

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +                clubNames.Append(this.listOfClubs[i].Name + ", ");
AppendJoin?

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public void CheckAllClubsPrices()
Check is misleading. Different name should be used

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public bool AddUserToClub(User user, string clubName)
AddUser is enough

2021-04-27 14:02 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/User.cs
> +        public string Name
Suggestion You can make use of the Auto-Implemented properties. Ref: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties

2021-04-28 16:27 UTC, GeorgiDyulgerov requested changes

2021-04-28 16:27 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/Club.cs
> +        public decimal CostOfAlcoholToDrink(int whiskeysToDrink, int vodkasToDrink)
Return type fixed but the name does not indicate you are GETing a result

2021-04-28 16:27 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public List<Club> listOfClubs = new List<Club>();
Can't it be private?

2021-04-28 16:27 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +                clubNames.AppendJoin(',', this.listOfClubs[i].Name);
Is this returning correct result? Please check

2021-04-28 16:27 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public void AlcoholPrices()
PrintAlcoholPrices tells us more

2021-04-28 16:27 UTC, GeorgiDyulgerov commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> -        public bool AddUserToClub(User user, string clubName)
Why delete this?

2021-05-21 14:07 UTC, Tanya-Zheleva commented on Drink_Book_PR/DrinkBook/ListsOfClubs.cs
> +        public List<Club> listOfClubs = new List<Club>();
This should be fixed

2021-06-09 12:08 UTC, merged